In [31]:
import pandas as pd

# read the xls files
df1 = pd.read_excel(
    # "./前一半_按文本_中国市场下的玄学因素对商品营销的成因与影响调研问卷_333_333.xlsx",
    "./前一半_按序号_中国市场下的玄学因素对商品营销的成因与影响调研问卷_333_333.xlsx",
    index_col=0,
)
df2 = pd.read_excel(
    # "./后一半_按文本_中国市场下的玄学因素对商品营销的成因与影响调研问卷_318_318.xlsx",
    "./后一半_按序号_中国市场下的玄学因素对商品营销的成因与影响调研问卷_318_318.xlsx",
    index_col=0,
)

In [32]:
df1

,提交答卷时间,所用时间,来源,来源详情,来自IP,总分,您的性别:,您的年龄:,您的学历水平:,您的专业/职业类别:,...,20(D. 其他),您认为“玄学营销”比较适合应用在哪些产业/品牌：(A. 餐饮/饮品（如咖啡店、茶饮、零食）),21(B. 时尚/饰品/美妆（如首饰、化妆品、服饰）),21(C. 文创/艺术/娱乐（如书籍、盲盒、演出、游戏）),21(D. 旅游/酒店/休闲（如祈福旅行、特色民宿）),21(E. 科技/互联网（如APP、线上占卜、虚拟产品）),21(F. 金融/理财（如带有寓意的理财产品、保险）),21(G. 其他),总体上，您是否接受“玄学营销”这种方式?,您对“玄学营销”还有什么别的看法吗？
序号,,,,,,,,,,,,,,,,,,,,,
1,2025/9/19 2:56:39,202秒,微信,NaN,37.166.243.34(国外-法国),23,1,2,3,7,...,4.0,0,1,0,0,1,0,0,4,没啦
2,2025/9/19 7:16:17,220秒,微信,NaN,39.146.41.239(安徽-合肥),22,2,5,4,2,...,4.0,1,1,0,0,1,0,0,5,跟民俗沾边，但轻松搞笑
3,2025/9/19 7:16:22,252秒,微信,NaN,120.239.125.209(广东-云浮),30,1,3,2,9,...,2.0,1,1,1,1,0,0,1,5,有趣，但不神圣
4,2025/9/19 7:17:34,265秒,微信,NaN,59.51.148.67(贵州-贵阳),9,2,4,2,12,...,4.0,1,1,0,0,0,0,0,2,跟时尚结合挺合适
5,2025/9/19 7:17:45,207秒,微信,NaN,112.19.42.232(四川-乐山),32,1,2,4,6,...,4.0,1,0,0,0,1,0,0,5,更像借文化包装
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,2025/9/20 19:02:16,157秒,微信,NaN,58.194.168.156(山东-济南),19,1,3,4,1,...,NaN,1,0,1,0,1,0,0,4,没有啦
330,2025/9/20 21:03:43,90秒,微信,NaN,112.96.113.142(广东-广州),24,2,3,3,2,...,NaN,1,1,1,1,0,0,0,3,无
331,2025/9/27 4:48:34,180秒,微信,NaN,80.215.161.46(国外-法国),22,1,2,4,1,...,NaN,0,1,1,0,1,0,0,3,无
332,2025/9/27 4:51:22,200秒,微信,NaN,37.65.12.131(国外-法国),28,1,2,4,3,...,NaN,1,0,1,1,1,0,0,4,很有意思，反映了市场选择
333,2025/10/6 6:15:06,721秒,微信,NaN,61.170.160.207(上海-上海),17,1,2,3,1,...,NaN,1,0,1,0,0,0,0,3,个人认为玄学销售与宗教信仰无关只是一种营销方式

In [34]:
df2

,提交答卷时间,所用时间,来源,来源详情,来自IP,总分,您的性别:,您的年龄:,您的学历水平:,您的专业/职业类别:,...,20(D. 其他),您认为“玄学营销”比较适合应用在哪些产业/品牌：(A. 餐饮/饮品（如咖啡店、茶饮、零食）),21(B. 时尚/饰品/美妆（如首饰、化妆品、服饰）),21(C. 文创/艺术/娱乐（如书籍、盲盒、演出、游戏）),21(D. 旅游/酒店/休闲（如祈福旅行、特色民宿）),21(E. 科技/互联网（如APP、线上占卜、虚拟产品）),21(F. 金融/理财（如带有寓意的理财产品、保险）),21(G. 其他),总体上，您是否接受“玄学营销”这种方式?,您对“玄学营销”还有什么别的看法吗？
序号,,,,,,,,,,,,,,,,,,,,,
1,2025/10/5 16:30:58,182秒,微信,NaN,163.179.41.163(广东-中山),29,1,4,2,3,...,3,1,1,1,1,0,0,0,4,个人觉得它有点“表演性质”，并不太相信能带来实际价值
2,2025/10/5 16:31:20,177秒,微信,NaN,112.132.8.142(安徽-阜阳),19,1,3,2,12,...,4,1,0,0,0,0,0,0,4,个人觉得它有点无聊，感觉就像在玩心理战
3,2025/10/5 16:32:05,261秒,微信,NaN,36.251.153.206(福建-泉州),30,2,3,1,6,...,4,0,1,1,0,1,0,0,4,不太相信这些，但看得多了也觉得它确实能引起话题
4,2025/10/5 16:33:12,253秒,微信,NaN,117.185.172.244(上海-上海),35,1,4,1,12,...,2,0,0,0,1,0,0,0,3,很多时候，玄学营销就像是个骗局，大家还是得小心
5,2025/10/5 16:34:22,167秒,微信,NaN,27.186.0.6(河北-保定),25,1,4,3,11,...,2,1,0,0,0,0,0,0,4,很多时候，玄学营销只是为了制造不确定性和惊奇感
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,2025/10/6 9:07:10,262秒,微信,NaN,123.88.33.64(广东-广州),26,1,3,2,4,...,1,1,0,1,0,0,0,0,3,通过“谜团”吸引你看
315,2025/10/6 9:08:01,164秒,微信,NaN,182.91.42.187(广西-桂林),34,2,3,2,6,...,4,1,1,1,0,0,0,0,3,吸引人，但没啥实质内容
316,2025/10/6 9:08:01,232秒,微信,NaN,61.141.154.29(广东-深圳),22,2,4,3,8,...,1,0,0,1,1,0,1,0,4,通过神秘感吸引了不少人
317,2025/10/6 9:10:24,170秒,微信,NaN,111.166.116.119(天津-天津),22,2,4,3,4,...,1,1,1,0,0,0,0,0,2,吸引人但不太实际，挺奇怪
318,2025/10/6 9:13:39,129秒,微信,NaN,120.235.23.65(广东-梅州),29,2,4,2,4,...,1,0,1,1,0,1,0,0,2,吸引我看，但不信它能持久

In [35]:
# merge the dataframes
merged_df = pd.concat([df1, df2], ignore_index=True)

In [36]:
merged_df.index += 1
merged_df.index.name = "序号"

In [37]:
merged_df

,提交答卷时间,所用时间,来源,来源详情,来自IP,总分,您的性别:,您的年龄:,您的学历水平:,您的专业/职业类别:,...,20(D. 其他),您认为“玄学营销”比较适合应用在哪些产业/品牌：(A. 餐饮/饮品（如咖啡店、茶饮、零食）),21(B. 时尚/饰品/美妆（如首饰、化妆品、服饰）),21(C. 文创/艺术/娱乐（如书籍、盲盒、演出、游戏）),21(D. 旅游/酒店/休闲（如祈福旅行、特色民宿）),21(E. 科技/互联网（如APP、线上占卜、虚拟产品）),21(F. 金融/理财（如带有寓意的理财产品、保险）),21(G. 其他),总体上，您是否接受“玄学营销”这种方式?,您对“玄学营销”还有什么别的看法吗？
序号,,,,,,,,,,,,,,,,,,,,,
1,2025/9/19 2:56:39,202秒,微信,NaN,37.166.243.34(国外-法国),23,1,2,3,7,...,4.0,0,1,0,0,1,0,0,4,没啦
2,2025/9/19 7:16:17,220秒,微信,NaN,39.146.41.239(安徽-合肥),22,2,5,4,2,...,4.0,1,1,0,0,1,0,0,5,跟民俗沾边，但轻松搞笑
3,2025/9/19 7:16:22,252秒,微信,NaN,120.239.125.209(广东-云浮),30,1,3,2,9,...,2.0,1,1,1,1,0,0,1,5,有趣，但不神圣
4,2025/9/19 7:17:34,265秒,微信,NaN,59.51.148.67(贵州-贵阳),9,2,4,2,12,...,4.0,1,1,0,0,0,0,0,2,跟时尚结合挺合适
5,2025/9/19 7:17:45,207秒,微信,NaN,112.19.42.232(四川-乐山),32,1,2,4,6,...,4.0,1,0,0,0,1,0,0,5,更像借文化包装
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,2025/10/6 9:07:10,262秒,微信,NaN,123.88.33.64(广东-广州),26,1,3,2,4,...,1.0,1,0,1,0,0,0,0,3,通过“谜团”吸引你看
648,2025/10/6 9:08:01,164秒,微信,NaN,182.91.42.187(广西-桂林),34,2,3,2,6,...,4.0,1,1,1,0,0,0,0,3,吸引人，但没啥实质内容
649,2025/10/6 9:08:01,232秒,微信,NaN,61.141.154.29(广东-深圳),22,2,4,3,8,...,1.0,0,0,1,1,0,1,0,4,通过神秘感吸引了不少人
650,2025/10/6 9:10:24,170秒,微信,NaN,111.166.116.119(天津-天津),22,2,4,3,4,...,1.0,1,1,0,0,0,0,0,2,吸引人但不太实际，挺奇怪
651,2025/10/6 9:13:39,129秒,微信,NaN,120.235.23.65(广东-梅州),29,2,4,2,4,...,1.0,0,1,1,0,1,0,0,2,吸引我看，但不信它能持久

In [38]:
# write the merged dataframe to a new xls file
merged_df.to_excel("按序号_merged.xlsx", na_rep="N/A")